--ANALISIS Y LIMPIEZA PARA LOS INDICADORES PR, HH Y QL PARA EL ESTADO DE TABASC0 POR MUNICIPIOS.
-- CLASIFICACION DE ACTIVIDADES IMPORTANTES EN LA REGION

use PR_HH_QL
GO

-- SELECCIONAMOS LOS VALORES POSITIVOS DE CADA AÑO Y PARA CADA MUNICIPIO 
SELECT H.AÑO, H.MUNICIPIO AS MUNICIPIO, H.ID_MUN_SEC_AÑO AS ID, H.HH_VACB AS HH_VACB
FROM HH_2$ as H
WHERE  H.AÑO = 2018 and HH_VACB > 0 
order by MUNICIPIO ASC, HH_VACB DESC

SELECT H.AÑO, H.MUNICIPIO AS MUNICIPIO, H.ID_MUN_SEC_AÑO AS ID, H.HH_VACB AS HH_VACB
FROM HH_2$ as H
WHERE  H.AÑO = 2013 and HH_VACB > 0 
order by MUNICIPIO ASC, HH_VACB DESC

SELECT H.AÑO, H.MUNICIPIO AS MUNICIPIO, H.ID_MUN_SEC_AÑO AS ID, H.HH_VACB AS HH_VACB
FROM HH_2$ as H
WHERE  H.AÑO = 2008 and HH_VACB > 0 
order by MUNICIPIO ASC, HH_VACB DESC

SELECT H.AÑO, H.MUNICIPIO AS MUNICIPIO, H.ID_MUN_SEC_AÑO AS ID, H.HH_VACB AS HH_VACB
FROM HH_2$ as H
WHERE  H.AÑO = 2003 and HH_VACB > 0 
order by MUNICIPIO ASC, HH_VACB DESC

-- CALCULO DE LA CANTIDAD DE ACTIVIDADES ECONOMICAS EN CADA UNO DE LOS MUNICIPIOS 

SELECT 2018 AS AÑO, QL.Municipio AS MUNICIPIO,COUNT(QL.Municipio) AS CUENTA
FROM QL_2$ AS QL
WHERE QL.AÑO = 2018
Group by QL.Municipio


SELECT 2013 AS AÑO, QL.Municipio AS MUNICIPIO,COUNT(QL.Municipio) AS CUENTA
FROM QL_2$ AS QL
WHERE QL.AÑO = 2013
Group by QL.Municipio


SELECT 2008 AS AÑO, QL.Municipio AS MUNICIPIO,COUNT(QL.Municipio) AS CUENTA
FROM QL_2$ AS QL
WHERE QL.AÑO = 2008
Group by QL.Municipio

SELECT 2003 AS AÑO, QL.Municipio AS MUNICIPIO,COUNT(QL.Municipio) AS CUENTA
FROM QL_2$ AS QL
WHERE QL.AÑO = 2003
Group by QL.Municipio

 --AHORA LO QUE NECESITAMOS ES QUE DE ACUERDO A LOS VALORES POSITIVOS QUE TENEMOS EN EL HH PARA CADA MUNICIPIO 
-- ME REGRESE LOS VALORES MAYORES A 0.005 EN EL PR Y LOS MAYORES A 1 EN EL QL EN EL CUAL HAYAN PASADO EL FILTRO DE UN HH>1
--

SELECT 2018 AS AÑO, H.Municipio AS MUNICIPIO, H.ID_MUN_SEC_AÑO AS ID, H.ID_SEC AS SECTOR, H.HH_VACB AS HH_VACB, PR.PR_VACB AS PR_VACB, QL.QL_VACB AS QL_VACB
FROM HH_2$ AS H
INNER JOIN [PR_2$] AS PR ON H.ID_MUN_SEC_AÑO = PR.ID_MUN_SEC_AÑO
INNER JOIN [QL_2$] AS QL ON PR.ID_MUN_SEC_AÑO = QL.ID_MUN_SEC_AÑO
WHERE H.HH_VACB > 0 AND PR.PR_VACB >0.005 AND QL.QL_VACB >1 AND H.AÑO = 2018
ORDER BY MUNICIPIO,HH_VACB  desc;

SELECT 2013 AS AÑO, H.Municipio AS MUNICIPIO, H.ID_MUN_SEC_AÑO AS ID, H.ID_SEC AS SECTOR, H.HH_VACB AS HH_VACB, PR.PR_VACB AS PR_VACB, QL.QL_VACB AS QL_VACB
FROM HH_2$ AS H
INNER JOIN [PR_2$] AS PR ON H.ID_MUN_SEC_AÑO = PR.ID_MUN_SEC_AÑO
INNER JOIN [QL_2$] AS QL ON PR.ID_MUN_SEC_AÑO = QL.ID_MUN_SEC_AÑO
WHERE H.HH_VACB > 0 AND PR.PR_VACB >0.005 AND QL.QL_VACB >1 AND H.AÑO = 2013
ORDER BY MUNICIPIO,HH_VACB  desc;

SELECT 2008 AS AÑO, H.Municipio AS MUNICIPIO, H.ID_MUN_SEC_AÑO AS ID, H.ID_SEC AS SECTOR, H.HH_VACB AS HH_VACB, PR.PR_VACB AS PR_VACB, QL.QL_VACB AS QL_VACB
FROM HH_2$ AS H
INNER JOIN [PR_2$] AS PR ON H.ID_MUN_SEC_AÑO = PR.ID_MUN_SEC_AÑO
INNER JOIN [QL_2$] AS QL ON PR.ID_MUN_SEC_AÑO = QL.ID_MUN_SEC_AÑO
WHERE H.HH_VACB > 0 AND PR.PR_VACB >0.005 AND QL.QL_VACB >1 AND H.AÑO = 2008
ORDER BY MUNICIPIO,HH_VACB  desc;

SELECT 2003 AS AÑO, H.Municipio AS MUNICIPIO, H.ID_MUN_SEC_AÑO AS ID, H.ID_SEC AS SECTOR, H.HH_VACB AS HH_VACB, PR.PR_VACB AS PR_VACB, QL.QL_VACB AS QL_VACB
FROM HH_2$ AS H
INNER JOIN [PR_2$] AS PR ON H.ID_MUN_SEC_AÑO = PR.ID_MUN_SEC_AÑO
INNER JOIN [QL_2$] AS QL ON PR.ID_MUN_SEC_AÑO = QL.ID_MUN_SEC_AÑO
WHERE H.HH_VACB > 0 AND PR.PR_VACB >0.005 AND QL.QL_VACB >1 AND H.AÑO = 2003
ORDER BY MUNICIPIO,HH_VACB  desc;

--EL SIGUIENTE PASO ES CONTAR EL NUMERO DE ACTIVIDADES QUE SON SIGNIFICATIVAS PARA LA REGION, ES DECIR AQUELLAS QUE TIENEN UN HH > 0 Y UN QL>1 


SELECT  H.AÑO,H.Municipio AS MUNICIPIO, COUNT(QL.QL_VACB) AS CUENTA
FROM HH_2$ AS H
INNER JOIN PR_2$ AS PR ON H.ID_MUN_SEC_AÑO = PR.ID_MUN_SEC_AÑO
INNER JOIN QL_2$ AS QL ON PR.ID_MUN_SEC_AÑO = QL.ID_MUN_SEC_AÑO
WHERE H.HH_VACB > 0 AND PR.PR_VACB >0.005 AND QL.QL_VACB >1 AND H.AÑO = 2018
GROUP BY H.Municipio, H.AÑO;

SELECT  H.AÑO,H.Municipio AS MUNICIPIO, COUNT(QL.QL_VACB) AS CUENTA
FROM HH_2$ AS H
INNER JOIN PR_2$ AS PR ON H.ID_MUN_SEC_AÑO = PR.ID_MUN_SEC_AÑO
INNER JOIN QL_2$ AS QL ON PR.ID_MUN_SEC_AÑO = QL.ID_MUN_SEC_AÑO
WHERE H.HH_VACB > 0 AND PR.PR_VACB >0.005 AND QL.QL_VACB >1 AND H.AÑO = 2013
GROUP BY H.Municipio, H.AÑO;

SELECT  H.AÑO,H.Municipio AS MUNICIPIO, COUNT(QL.QL_VACB) AS CUENTA
FROM HH_2$ AS H
INNER JOIN PR_2$ AS PR ON H.ID_MUN_SEC_AÑO = PR.ID_MUN_SEC_AÑO
INNER JOIN QL_2$ AS QL ON PR.ID_MUN_SEC_AÑO = QL.ID_MUN_SEC_AÑO
WHERE H.HH_VACB > 0 AND PR.PR_VACB >0.005 AND QL.QL_VACB >1 AND H.AÑO = 2008
GROUP BY H.Municipio, H.AÑO;

SELECT  H.AÑO,H.Municipio AS MUNICIPIO, COUNT(QL.QL_VACB) AS CUENTA
FROM HH_2$ AS H
INNER JOIN PR_2$ AS PR ON H.ID_MUN_SEC_AÑO = PR.ID_MUN_SEC_AÑO
INNER JOIN QL_2$ AS QL ON PR.ID_MUN_SEC_AÑO = QL.ID_MUN_SEC_AÑO
WHERE H.HH_VACB > 0 AND PR.PR_VACB >0.005 AND QL.QL_VACB >1 AND H.AÑO = 2003
GROUP BY H.Municipio, H.AÑO;


